version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDER=POSTGRES
      - DB_ADDR=host.docker.internal
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 8080:8080
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432